name: Release

on:
  push:
    branches:
      - master
      - next
      - beta
      - "*.x"

env:
  DOCKER_USERNAME: containersolution
  DOCKER_REPOSITORY_NAME: semver
  #DOCKER_REPOSITORY: '$(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_REPOSITORY_NAME)'

jobs:


  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install -g semantic-release @semantic-release/exec semantic-release-plus @semantic-release-plus/docker
      - run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


